Remove unnecessary config options from BoardConfig

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -14,42 +14,74 @@ env:
   GP2040_REPO: OpenStickCommunity/GP2040-CE
 
 jobs:
-  get-release-version:
-    if: ${{ github.ref == 'refs/heads/main' }}
+  get-tags:
     runs-on: ubuntu-latest
+    outputs:
+      next_tag: ${{ steps.tags.outputs.next_tag }}
+      gp2040_ce_tag: ${{ steps.tags.outputs.gp2040_ce_tag }}
     steps:
-    - run: |  
+    - if: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
+      run: |
         TAG=$(gh release view --repo '${{ env.GP2040_REPO }}' --json tagName --jq .tagName || echo)
         echo 'GP2040_CE_TAG='$TAG >> $GITHUB_ENV
+        echo 'CURRENT_TAG=' >> $GITHUB_ENV
       env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         OWNER: ${{ github.repository_owner }}
         REPO: ${{ github.event.repository.name }}
-    - run: |
+
+    - if: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
+      run: |
         TAG=$(gh release view --repo '${{ github.repository }}' --json tagName --jq .tagName || echo)
-        echo 'CURRENT_TAG='$TAG >> $GITHUB_ENV
+        echo 'LAST_TAG='$TAG >> $GITHUB_ENV
       env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         OWNER: ${{ github.repository_owner }}
         REPO: ${{ github.event.repository.name }}
-    - run: touch ${{github.workspace}}/release_version.txt
-    - if: ${{ env.GP2040_CE_TAG != 'release not found' && env.GP2040_CE_TAG != env.CURRENT_TAG }}
-      run: echo $GP2040_CE_TAG > ${{github.workspace}}/release_version.txt
-    - uses: actions/upload-artifact@v4.3.1
-      with:
-        name: Release Version
-        path: ${{github.workspace}}/release_version.txt
-        if-no-files-found: error
+
+    - if: ${{ github.ref_type == 'tag' }}
+      run: |
+        echo 'CURRENT_TAG='$(echo ${{ github.ref_name }} | sed -E 's/^(v[0-9]+\.[0-9]+\.[0-9]+).*/\1/g') >> $GITHUB_ENV
+
+    - if: ${{ github.ref_type == 'tag' }}
+      run: |
+        TAG=$(gh release view --repo '${{ env.GP2040_REPO }}' '${{ env.CURRENT_TAG }}' --json tagName --jq .tagName || echo)
+        if [ $TAG == 'release not found' ] || [ $TAG == '' ]; then
+          >&2 echo "Couldn't find GP2040 release!"
+          exit 1
+        fi
+      env:
+        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        OWNER: ${{ github.repository_owner }}
+        REPO: ${{ github.event.repository.name }}
+
+    - if: ${{ env.GP2040_CE_TAG == 'release not found' || env.GP2040_CE_TAG == '' }}
+      run: |
+        >&2 echo "Couldn't find GP2040 release!"
+        exit 1
+
+    - id: tags
+      run: |
+        echo 'gp2040_ce_tag='${{ env.GP2040_CE_TAG }} >> "$GITHUB_OUTPUT"
+        if [ ${{ env.GP2040_CE_TAG }} != $CURRENT_TAG ]; then
+          echo 'next_tag='${{ env.GP2040_CE_TAG}} >> "$GITHUB_OUTPUT"
+        else
+          echo 'next_tag=' >> $GITHUB_OUTPUT
+        fi
 
   build-web-interface:
     uses: ./.github/workflows/node.js.yml
 
   build-firmware:
-    needs: build-web-interface
+    needs:
+      - build-web-interface
+      - get-tags
     # The CMake configure and build commands are platform-agnostic and should work equally well on Windows or Mac.
     # You can convert this to a matrix build if you need cross-platform coverage.
     # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
     runs-on: ubuntu-latest
+    env:
+      GP2040_CE_TAG: ${{needs.get-tags.outputs.gp2040_ce_tag}}
 
     steps:
     #Global Setup
@@ -57,13 +89,14 @@ jobs:
       uses: actions/checkout@v4.1.1
       with:
         repository: '${{ env.GP2040_REPO }}'
+        ref: '${{ env.GP2040_CE_TAG }}'
         fetch-depth: 0
         fetch-tags: true
 
     - name: Checkout IPFB
       uses: actions/checkout@v4.1.1
       with:
-        path: configs/${{ env.GP2040_BOARDCONFIG }}/
+        path: configs/${{ env.GP2040_BOARDCONFIG }}
 
     - name: Setup SDK pipeline
       uses: Fortinbra/RaspberryPiPicoBuild@v3
@@ -76,7 +109,7 @@ jobs:
 
     - name: Get core count
       id: core_count
-      run : cat /proc/cpuinfo  | grep processor | wc -l
+      run: echo 'output='$(cat /proc/cpuinfo | grep processor | wc -l) >> "$GITHUB_OUTPUT"
       #End Global Setup
 
     - name: Pico Build Configure CMake
@@ -98,28 +131,20 @@ jobs:
     permissions:
       contents: write
     needs:
-      - get-release-version
+      - get-tags
       - build-firmware
-    if: ${{ github.ref == 'refs/heads/main' }}
+    env:
+      RELEASE_VERSION: ${{needs.get-tags.outputs.next_tag}}
+    if: ${{ github.ref == 'refs/heads/main' && needs.get-tags.outputs.next_tag != '' }}
     runs-on: ubuntu-latest
     steps:
-      - name: Get Release Version
-        uses: actions/download-artifact@v4.1.2
-        with:
-          name: Release Version
-          path: ${{github.workspace}}/
-
-      - run: echo "RELEASE_VERSION=$(cat release_version.txt)" >> $GITHUB_ENV
-
       - name: Download Build Artifacts
-        if: ${{ env.RELEASE_VERSION != '' }}
         uses: actions/download-artifact@v4.1.2
         with:
           name: GP2040-CE - ${{ env.GP2040_BOARDCONFIG }}
           path: ${{github.workspace}}/
 
       - name: Create Release
-        if: ${{ env.RELEASE_VERSION != '' }}
         run: gh release create --repo '${{ github.repository }}' --notes "This is an automated release. See the GP2040-CE patch notes for ${{ env.RELEASE_VERSION }} [here](https://github.com/${{ env.GP2040_REPO }}/releases/tag/${{ env.RELEASE_VERSION }})." ${{ env.RELEASE_VERSION }} ./*.uf2
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
